name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev \
            libxcursor-dev libxinerama-dev libwayland-dev \
            libxkbcommon-dev

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel

      - name: Prepare distribution folder
        shell: bash
        run: |
          mkdir -p dist
          mkdir -p srv

          find build -type f \( -name "shooter" -o -name "shooter.exe" \) -exec cp {} dist/ \;
          find build -type f \( -name "shooter-server" -o -name "shooter-server.exe" \) -exec cp {} srv/ \;

          cp -r assets dist/

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: shootan-${{ matrix.os }}
          path: dist/

      - name: Upload server build artifact
        uses: actions/upload-artifact@v4
        with:
          name: shootan-server${{ matrix.os }}
          path: srv/